### ISSUE TITLE
Using ImageMagick's "animate" tool

### ISSUE THREAD

**Issue by samer** [arduino/openwrt-packages-yun#14]
Hello,
I have installed the following packages:
```
imagemagick
imagemagick-tools
imagemagick-jpeg
imagemagick-png
```
I'm trying to create an animated GIF using two JPEGs. using `animate 116.jpg 117.jpg`
I get the following error:
```
animate: DelegateLibrarySupportNotBuiltIn `' (X11) @ error/animate.c/AnimateImageCommand/1472.
```
Any idea how to resolve this?

**Comment by ffissore** [comment]
Reopen with the proposed fix when ready
