### ISSUE TITLE
python-netifaces

### ISSUE THREAD

**Issue by XVII** [arduino/openwrt-packages-yun#30]
Does anyone have an ipkg for python-netifaces or instructions on how to cross-compile?

The build with **mips-openwrt-linux-uclibc-gcc** using pip fails with;
    mips-openwrt-linux-uclibc-gcc -fno-strict-aliasing -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -DNDEBUG -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -fPIC -DNETIFACES_VERSION=0.10.6 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-mips-2.7/netifaces.o
    cc1: error: unrecognized command line option '-fhonour-copts'

**Comment by nxhack** [comment]
LEDE-17.01 & LEDE trunk with musl is working. For your information.

https://github.com/nxhack/openwrt-custom-packages/blob/master/python-netifaces/Makefile

**Comment by facchinm** [comment]
Hi @ShadowXVII ,
if you update your Yun to https://github.com/arduino/lede-yun the package linked by @nxhack  can be compiled seamlessly. The link for the new cross toolchain is https://downloads.arduino.cc/openwrtyun/17.11/packages/targets/ar71xx/generic/ledeyun-sdk-17.11-ar71xx-generic_gcc-5.5.0_musl.Linux-x86_64.tar.xz

**Comment by XVII** [comment]
Oh sweet didn't realise there was a LEDE version of the Yun image. I'll give it a go. Thanks :)

**Comment by XVII** [comment]
Great got the new image setup. 

⚠️Stupid question -- how do I compile/use that repo :P :) #PackageN00b 
Also, where do I get the distribute package from 🤔

**Comment by nxhack** [comment]
@ShadowXVII 

If you just build the package,
https://openwrt.org/docs/guide-developer/build-system/install-buildsystem

In the case of Debian 9.3 Stretch:
```
sudo apt install build-essential libncurses5-dev gawk git subversion libssl-dev gettext zlib1g-dev
mkdir Build_Path_Some_Where
cd Build_Path_Some_Where
wget https://downloads.arduino.cc/openwrtyun/17.11/packages/targets/ar71xx/generic/ledeyun-sdk-17.11-ar71xx-generic_gcc-5.5.0_musl.Linux-x86_64.tar.xz
tar xfJ ledeyun-sdk-17.11-ar71xx-generic_gcc-5.5.0_musl.Linux-x86_64.tar.xz
cd ledeyun-sdk-17.11-ar71xx-generic_gcc-5.5.0_musl.Linux-x86_64
echo "src-git mycustom https://github.com/nxhack/openwrt-custom-packages.git" >> feeds.conf.default
./scripts/feeds update -a
./scripts/feeds install -a
make package/feeds/mycustom/python-netifaces/{download,prepare,compile} V=s

ls -l ./bin/packages/mips_24kc/mycustom/
```

Perhaps you will also need lede-yun firmware for this environment.
There may be comments from @facchinm

**Comment by XVII** [comment]
That worked -- thanks @nxhack 👍
